# Generated by Django 5.1.7 on 2025-03-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('adress', models.TextField(blank=True, null=True)),
                ('login', models.CharField(default='', max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('adress_latitude', models.FloatField()),
                ('adress_longitude', models.FloatField()),
                ('trash_info', models.JSONField()),
                ('trash_section', models.TextField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
