# Generated by Django 5.1.7 on 2025-03-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_coleta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste_Api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('numero_teste', models.TextField(blank=True)),
                ('nome', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Teste_API_',
            },
        ),
    ]
