# Generated by Django 5.1.7 on 2025-03-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa_coleta', '0002_teste_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enderecos_Pontos_Lixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('endereco', models.TextField(blank=True)),
                ('tipo_lixeira', models.TextField(blank=True, null=True)),
                ('tipo_lixo', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longetude', models.FloatField()),
            ],
            options={
                'db_table': 'endereco_pontos_lixo',
            },
        ),
    ]
